### ISSUE TITLE
Keep modification time the same as the original file

### ISSUE THREAD

**Issue by avdv** [ember-cli-deploy/ember-cli-deploy-gzip#32]
When using the `gzip_static` on` directive of nginx, the [manual](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html#gzip_static) says:

> The files can be compressed using the gzip command, or any other compatible one. It is recommended that the modification date and time of original and compressed files be the same.

**Comment by caljess599** [comment]
I'm also trying to use this plugin in combination with nginx's `gzip_static` directive. Modern versions of nginx don't require the uncompressed files to be present in addition to the compressed ones, but what I am finding is that nginx seems to expect a gzipped file to have the `.gz` extension. So what I'd be looking for is a version of the `keep` setting that allows compressed files to be renamed rather than keeping the original alongside the compressed version.

**Comment by lukemelia** [comment]
@avdv @caljess599 These both seems like reasonable additions to this plugin. I'm happy to review a PR for one or both of them.
